export const PLATFORMS_DATA = [
  // Ticketmaster Plattformen
  { name: 'Ticketmaster Australia', slug: 'ticketmaster-au', category: 'ticketing', country: 'Australia', domain: 'ticketmaster.com.au' },
  { name: 'Ticketmaster Austria', slug: 'ticketmaster-at', category: 'ticketing', country: 'Austria', domain: 'ticketmaster.at' },
  { name: 'Ticketmaster Belgium', slug: 'ticketmaster-be', category: 'ticketing', country: 'Belgium', domain: 'ticketmaster.be' },
  { name: 'Ticketmaster Canada', slug: 'ticketmaster-ca', category: 'ticketing', country: 'Canada', domain: 'ticketmaster.ca' },
  { name: 'Ticketmaster Czech Republic', slug: 'ticketmaster-cz', category: 'ticketing', country: 'Czech Republic', domain: 'ticketmaster.cz' },
  { name: 'Ticketmaster Denmark', slug: 'ticketmaster-dk', category: 'ticketing', country: 'Denmark', domain: 'ticketmaster.dk' },
  { name: 'Ticketmaster Finland', slug: 'ticketmaster-fi', category: 'ticketing', country: 'Finland', domain: 'ticketmaster.fi' },
  { name: 'Ticketmaster Germany', slug: 'ticketmaster-de', category: 'ticketing', country: 'Germany', domain: 'ticketmaster.de' },
  { name: 'Ticketmaster Ireland', slug: 'ticketmaster-ie', category: 'ticketing', country: 'Ireland', domain: 'ticketmaster.ie' },
  { name: 'Ticketmaster Mexico', slug: 'ticketmaster-mx', category: 'ticketing', country: 'Mexico', domain: 'ticketmaster.com.mx' },
  { name: 'Ticketmaster Netherlands', slug: 'ticketmaster-nl', category: 'ticketing', country: 'Netherlands', domain: 'ticketmaster.nl' },
  { name: 'Ticketmaster New Zealand', slug: 'ticketmaster-nz', category: 'ticketing', country: 'New Zealand', domain: 'ticketmaster.co.nz' },
  { name: 'Ticketmaster Norway', slug: 'ticketmaster-no', category: 'ticketing', country: 'Norway', domain: 'ticketmaster.no' },
  { name: 'Ticketmaster Poland', slug: 'ticketmaster-pl', category: 'ticketing', country: 'Poland', domain: 'ticketmaster.pl' },
  { name: 'Ticketmaster South Africa', slug: 'ticketmaster-za', category: 'ticketing', country: 'South Africa', domain: 'ticketmaster.co.za' },
  { name: 'Ticketmaster Spain', slug: 'ticketmaster-es', category: 'ticketing', country: 'Spain', domain: 'ticketmaster.es' },
  { name: 'Ticketmaster Sweden', slug: 'ticketmaster-se', category: 'ticketing', country: 'Sweden', domain: 'ticketmaster.se' },
  { name: 'Ticketmaster Switzerland', slug: 'ticketmaster-ch', category: 'ticketing', country: 'Switzerland', domain: 'ticketmaster.ch' },
  { name: 'Ticketmaster United Arab Emirates', slug: 'ticketmaster-ae', category: 'ticketing', country: 'United Arab Emirates', domain: 'ticketmaster.ae' },
  { name: 'Ticketmaster United Kingdom', slug: 'ticketmaster-uk', category: 'ticketing', country: 'United Kingdom', domain: 'ticketmaster.co.uk' },
  { name: 'Ticketmaster United States', slug: 'ticketmaster-us', category: 'ticketing', country: 'United States', domain: 'ticketmaster.com' },

  // Eventim Plattformen
  { name: 'Eventim Austria', slug: 'eventim-at', category: 'ticketing', country: 'Austria', domain: 'oeticket.com' },
  { name: 'Eventim Brazil', slug: 'eventim-br', category: 'ticketing', country: 'Brazil', domain: 'eventim.com.br' },
  { name: 'Eventim Bulgaria', slug: 'eventim-bg', category: 'ticketing', country: 'Bulgaria', domain: 'eventim.bg' },
  { name: 'Eventim Canada', slug: 'eventim-ca', category: 'ticketing', country: 'Canada', domain: 'eventim.ca' },
  { name: 'Eventim Croatia', slug: 'eventim-hr', category: 'ticketing', country: 'Croatia', domain: 'eventim.hr' },
  { name: 'Eventim Denmark', slug: 'eventim-dk', category: 'ticketing', country: 'Denmark', domain: 'eventim.dk' },
  { name: 'Eventim Germany', slug: 'eventim-de', category: 'ticketing', country: 'Germany', domain: 'eventim.de' },
  { name: 'Eventim Finland', slug: 'eventim-fi', category: 'ticketing', country: 'Finland', domain: 'lippu.fi' },
  { name: 'Eventim France', slug: 'eventim-fr', category: 'ticketing', country: 'France', domain: 'eventim.fr' },
  { name: 'Eventim Hungary', slug: 'eventim-hu', category: 'ticketing', country: 'Hungary', domain: 'eventim.hu' },
  { name: 'Eventim Italy', slug: 'eventim-it', category: 'ticketing', country: 'Italy', domain: 'ticketone.it' },
  { name: 'Eventim Netherlands', slug: 'eventim-nl', category: 'ticketing', country: 'Netherlands', domain: 'eventim.nl' },
  { name: 'Eventim Norway', slug: 'eventim-no', category: 'ticketing', country: 'Norway', domain: 'eventim.no' },
  { name: 'Eventim Poland', slug: 'eventim-pl', category: 'ticketing', country: 'Poland', domain: 'eventim.pl' },
  { name: 'Eventim Romania', slug: 'eventim-ro', category: 'ticketing', country: 'Romania', domain: 'eventim.ro' },
  { name: 'Eventim Slovakia', slug: 'eventim-sk', category: 'ticketing', country: 'Slovakia', domain: 'eventim.sk' },
  { name: 'Eventim Slovenia', slug: 'eventim-si', category: 'ticketing', country: 'Slovenia', domain: 'eventim.si' },
  { name: 'Eventim Spain', slug: 'eventim-es', category: 'ticketing', country: 'Spain', domain: 'entradas.com' },
  { name: 'Eventim Sweden', slug: 'eventim-se', category: 'ticketing', country: 'Sweden', domain: 'eventim.se' },
  { name: 'Eventim Switzerland', slug: 'eventim-ch', category: 'ticketing', country: 'Switzerland', domain: 'ticketcorner.ch' },
  { name: 'Eventim United Kingdom', slug: 'eventim-uk', category: 'ticketing', country: 'United Kingdom', domain: 'eventim.co.uk' },
  { name: 'Eventim United States', slug: 'eventim-us', category: 'ticketing', country: 'United States', domain: 'eventim.com' },

  // Fansale Plattformen
  { name: 'Fansale Austria', slug: 'fansale-at', category: 'ticketing', country: 'Austria', domain: 'fansale.at' },
  { name: 'Fansale Brazil', slug: 'fansale-br', category: 'ticketing', country: 'Brazil', domain: 'fansale.com.br' },
  { name: 'Fansale Denmark', slug: 'fansale-dk', category: 'ticketing', country: 'Denmark', domain: 'fansale.dk' },
  { name: 'Fansale Finland', slug: 'fansale-fi', category: 'ticketing', country: 'Finland', domain: 'fansale.fi' },
  { name: 'Fansale Germany', slug: 'fansale-de', category: 'ticketing', country: 'Germany', domain: 'fansale.de' },
  { name: 'Fansale Italy', slug: 'fansale-it', category: 'ticketing', country: 'Italy', domain: 'fansale.it' },
  { name: 'Fansale Netherlands', slug: 'fansale-nl', category: 'ticketing', country: 'Netherlands', domain: 'fansale.nl' },
  { name: 'Fansale Norway', slug: 'fansale-no', category: 'ticketing', country: 'Norway', domain: 'fansale.no' },
  { name: 'Fansale Poland', slug: 'fansale-pl', category: 'ticketing', country: 'Poland', domain: 'fansale.pl' },
  { name: 'Fansale Spain', slug: 'fansale-es', category: 'ticketing', country: 'Spain', domain: 'fansale.es' },
  { name: 'Fansale Sweden', slug: 'fansale-se', category: 'ticketing', country: 'Sweden', domain: 'fansale.se' },
  { name: 'Fansale Switzerland', slug: 'fansale-ch', category: 'ticketing', country: 'Switzerland', domain: 'fansale.ch' },
  { name: 'Fansale United Kingdom', slug: 'fansale-uk', category: 'ticketing', country: 'United Kingdom', domain: 'fansale.co.uk' },
  { name: 'Fansale United States', slug: 'fansale-us', category: 'ticketing', country: 'United States', domain: 'eventim-exchange.com' },

  // Twickets Plattformen
  { name: 'Twickets Australia', slug: 'twickets-au', category: 'ticketing', country: 'Australia', domain: 'twickets.com' },
  { name: 'Twickets Austria', slug: 'twickets-at', category: 'ticketing', country: 'Austria', domain: 'twickets.com' },
  { name: 'Twickets United Arab Emirates', slug: 'twickets-ae', category: 'ticketing', country: 'United Arab Emirates', domain: 'twickets.com' },
  { name: 'Twickets Belgium', slug: 'twickets-be', category: 'ticketing', country: 'Belgium', domain: 'twickets.com' },
  { name: 'Twickets Brazil', slug: 'twickets-br', category: 'ticketing', country: 'Brazil', domain: 'twickets.com' },
  { name: 'Twickets Canada', slug: 'twickets-ca', category: 'ticketing', country: 'Canada', domain: 'twickets.com' },
  { name: 'Twickets Czech Republic', slug: 'twickets-cz', category: 'ticketing', country: 'Czechia', domain: 'twickets.com' },
  { name: 'Twickets Denmark', slug: 'twickets-dk', category: 'ticketing', country: 'Denmark', domain: 'twickets.com' },
  { name: 'Twickets France', slug: 'twickets-fr', category: 'ticketing', country: 'France', domain: 'twickets.com' },
  { name: 'Twickets Germany', slug: 'twickets-de', category: 'ticketing', country: 'Germany', domain: 'twickets.com' },
  { name: 'Twickets Hong Kong', slug: 'twickets-hk', category: 'ticketing', country: 'Hong Kong', domain: 'twickets.com' },
  { name: 'Twickets Hungary', slug: 'twickets-hu', category: 'ticketing', country: 'Hungary', domain: 'twickets.com' },
  { name: 'Twickets Iceland', slug: 'twickets-is', category: 'ticketing', country: 'Iceland', domain: 'twickets.com' },
  { name: 'Twickets Ireland', slug: 'twickets-ie', category: 'ticketing', country: 'Ireland', domain: 'twickets.com' },
  { name: 'Twickets Italy', slug: 'twickets-it', category: 'ticketing', country: 'Italy', domain: 'twickets.com' },
  { name: 'Twickets Malta', slug: 'twickets-mt', category: 'ticketing', country: 'Malta', domain: 'twickets.com' },
  { name: 'Twickets Mexico', slug: 'twickets-mx', category: 'ticketing', country: 'Mexico', domain: 'twickets.com' },
  { name: 'Twickets Monaco', slug: 'twickets-mc', category: 'ticketing', country: 'Monaco', domain: 'twickets.com' },
  { name: 'Twickets Netherlands', slug: 'twickets-nl', category: 'ticketing', country: 'Netherlands', domain: 'twickets.com' },
  { name: 'Twickets New Zealand', slug: 'twickets-nz', category: 'ticketing', country: 'New Zealand', domain: 'twickets.com' },
  { name: 'Twickets Norway', slug: 'twickets-no', category: 'ticketing', country: 'Norway', domain: 'twickets.com' },
  { name: 'Twickets Poland', slug: 'twickets-pl', category: 'ticketing', country: 'Poland', domain: 'twickets.com' },
  { name: 'Twickets Portugal', slug: 'twickets-pt', category: 'ticketing', country: 'Portugal', domain: 'twickets.com' },
  { name: 'Twickets Spain', slug: 'twickets-es', category: 'ticketing', country: 'Spain', domain: 'twickets.com' },
  { name: 'Twickets Sweden', slug: 'twickets-se', category: 'ticketing', country: 'Sweden', domain: 'twickets.com' },
  { name: 'Twickets Switzerland', slug: 'twickets-ch', category: 'ticketing', country: 'Switzerland', domain: 'twickets.com' },
  { name: 'Twickets United Kingdom', slug: 'twickets-uk', category: 'ticketing', country: 'United Kingdom', domain: 'twickets.com' },
  { name: 'Twickets United States', slug: 'twickets-us', category: 'ticketing', country: 'United States', domain: 'twickets.com' },

  // Sports Plattformen
  { name: 'DFB Pokal', slug: 'dfb-pokal', category: 'sports', country: 'Germany', domain: 'dfb.de' },
  { name: 'UEFA Champions League', slug: 'uefa-champions-league', category: 'sports', country: 'International', domain: 'uefa.com' },
  { name: 'UEFA EURO', slug: 'uefa-euro', category: 'sports', country: 'International', domain: 'uefa.com' },
  { name: 'UEFA Europa Conference League', slug: 'uefa-europa-conference-league', category: 'sports', country: 'International', domain: 'uefa.com' },
  { name: 'UEFA Europa League', slug: 'uefa-europa-league', category: 'sports', country: 'International', domain: 'uefa.com' },
  { name: 'UEFA Super Cup', slug: 'uefa-super-cup', category: 'sports', country: 'International', domain: 'uefa.com' },
  { name: 'MLB', slug: 'mlb', category: 'sports', country: 'United States', domain: 'mlb.com' }
];
